In [1]:
#importing necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.metrics import ConfusionMatrixDisplay
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold, cross_val_score
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.pipeline import Pipeline                  # Combine preprocessing and models
from sklearn.preprocessing import StandardScaler 
from sklearn.metrics import mean_absolute_error

# PART 1 - Data Exploration and Data Cleaning

In [2]:
#reading in dataset
ds = pd.read_csv('abalone.csv')
ds

,Sex,Length,Diameter,Height,Whole_weight,Shucked_weight,Viscera_weight,Shell_weight,Rings
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550,7
...,...,...,...,...,...,...,...,...,...
4175,F,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490,11
4176,M,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605,10
4177,M,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080,9
4178,F,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960,10
4179,M,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950,12

In [3]:
#checking head
ds.head()

,Sex,Length,Diameter,Height,Whole_weight,Shucked_weight,Viscera_weight,Shell_weight,Rings
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055,7

In [4]:
#checking tail
ds.tail()

,Sex,Length,Diameter,Height,Whole_weight,Shucked_weight,Viscera_weight,Shell_weight,Rings
4175,F,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490,11
4176,M,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605,10
4177,M,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080,9
4178,F,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960,10
4179,M,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950,12

In [5]:
#checking unique values for sex
ds['Sex'].unique()

array(['M', 'F', 'I'], dtype=object)

In [6]:
#checking the number of duplicates
ds.duplicated().sum()

np.int64(3)

In [7]:
#checking number of nulls in dataset
print(ds.isnull().sum())

Sex               0
Length            0
Diameter          0
Height            8
Whole_weight      0
Shucked_weight    5
Viscera_weight    5
Shell_weight      0
Rings             0
dtype: int64

In [8]:
#going to start cleaning
df = pd.DataFrame(ds)
df.head()

,Sex,Length,Diameter,Height,Whole_weight,Shucked_weight,Viscera_weight,Shell_weight,Rings
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055,7

In [ ]:
df.shape